name: Trigger-backend
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Trigger-backend
    runs-on: ubuntu-latest
    steps:
      - name: Trigger-backend
        run: |
          echo "Trigger-backend"
          sleep 10s
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: vicky0048
          repo: github-actions
          github_token: ${{ secrets.REPOSITORY_TOKEN }}
          workflow_file_name: maven.yml
          ref: master
      - name: Trigger-backend
        run: |
          echo "Trigger-backend"
          sleep 10s
